adjlist:
  client1:
    switch5: 0
  client10:
    switch13: 0
  client2:
    switch6: 0
  client3:
    switch7: 0
  client4:
    switch8: 0
  client5:
    switch9: 0
  client6:
    switch10: 0
  client7:
    switch11: 0
  client8:
    switch12: 0
  client9:
    switch13: 0
  server1:
    switch14: 0
  server2:
    switch14: 0
  server3:
    switch14: 0
  server4:
    switch14: 0
  server5:
    switch14: 0
  server6:
    switch14: 0
  switch1:
    switch14: 4
    switch2: 1
    switch3: 2
    switch4: 3
  switch10:
    client6: 1
    switch3: 2
  switch11:
    client7: 1
    switch4: 2
  switch12:
    client8: 1
    switch4: 2
  switch13:
    client10: 2
    client9: 1
    switch4: 3
  switch14:
    server1: 2
    server2: 3
    server3: 4
    server4: 5
    server5: 6
    server6: 7
    switch1: 1
  switch2:
    switch1: 1
    switch5: 2
    switch6: 3
    switch7: 4
  switch3:
    switch1: 1
    switch10: 4
    switch8: 2
    switch9: 3
  switch4:
    switch1: 1
    switch11: 2
    switch12: 3
    switch13: 4
  switch5:
    client1: 1
    switch2: 2
  switch6:
    client2: 1
    switch2: 2
  switch7:
    client3: 1
    switch2: 2
  switch8:
    client4: 1
    switch3: 2
  switch9:
    client5: 1
    switch3: 2
core_switch: switch1
edge_switches:
- switch5
- switch6
- switch7
- switch8
- switch9
- switch10
- switch11
- switch12
- switch13
edgelist: !!set
  ? !!python/tuple
  - client1
  - switch5
  - 0
  - 1
  : null
  ? !!python/tuple
  - client10
  - switch13
  - 0
  - 2
  : null
  ? !!python/tuple
  - client2
  - switch6
  - 0
  - 1
  : null
  ? !!python/tuple
  - client3
  - switch7
  - 0
  - 1
  : null
  ? !!python/tuple
  - client4
  - switch8
  - 0
  - 1
  : null
  ? !!python/tuple
  - client5
  - switch9
  - 0
  - 1
  : null
  ? !!python/tuple
  - client6
  - switch10
  - 0
  - 1
  : null
  ? !!python/tuple
  - client7
  - switch11
  - 0
  - 1
  : null
  ? !!python/tuple
  - client8
  - switch12
  - 0
  - 1
  : null
  ? !!python/tuple
  - client9
  - switch13
  - 0
  - 1
  : null
  ? !!python/tuple
  - server1
  - switch14
  - 0
  - 2
  : null
  ? !!python/tuple
  - server2
  - switch14
  - 0
  - 3
  : null
  ? !!python/tuple
  - server3
  - switch14
  - 0
  - 4
  : null
  ? !!python/tuple
  - server4
  - switch14
  - 0
  - 5
  : null
  ? !!python/tuple
  - server5
  - switch14
  - 0
  - 6
  : null
  ? !!python/tuple
  - server6
  - switch14
  - 0
  - 7
  : null
  ? !!python/tuple
  - switch1
  - switch14
  - 4
  - 1
  : null
  ? !!python/tuple
  - switch1
  - switch2
  - 1
  - 1
  : null
  ? !!python/tuple
  - switch1
  - switch3
  - 2
  - 1
  : null
  ? !!python/tuple
  - switch1
  - switch4
  - 3
  - 1
  : null
  ? !!python/tuple
  - switch10
  - switch3
  - 2
  - 4
  : null
  ? !!python/tuple
  - switch11
  - switch4
  - 2
  - 2
  : null
  ? !!python/tuple
  - switch12
  - switch4
  - 2
  - 3
  : null
  ? !!python/tuple
  - switch13
  - switch4
  - 3
  - 4
  : null
  ? !!python/tuple
  - switch2
  - switch5
  - 2
  - 2
  : null
  ? !!python/tuple
  - switch2
  - switch6
  - 3
  - 2
  : null
  ? !!python/tuple
  - switch2
  - switch7
  - 4
  - 2
  : null
  ? !!python/tuple
  - switch3
  - switch8
  - 2
  - 2
  : null
  ? !!python/tuple
  - switch3
  - switch9
  - 3
  - 2
  : null
internal_switches:
- switch2
- switch3
- switch4
list_clients:
- client1
- client2
- client3
- client4
- client5
- client6
- client7
- client8
- client9
- client10
list_servers:
- server1
- server2
- server3
- server4
- server5
- server6
server_switch: switch14
