topology: 
  zoo_data: 
    details: 
      filename: Kreonet.graphml
      client_switches: 12
      clients: 24
  mesh: 
    details: 
      switches: 5
      client_switches: 4
      clients: 24
  fat_tree: 
    details: 
      clients : 24
      leaf_switch_layers : 2
      fanout: 3