topology: 
  mesh: 
    details: 
      switches: 5
      client_switches: 4
      clients: 24
  fat_tree: 
    details: 
      clients : 24
      leaf_switch_layers : 2
      fanout: 3
  zoo_data: 
    details: 
      filename: UniC.graphml
      client_switches: 24
      clients: 24
