topology :
  zoo_data:
    details:
      filename: UniC.graphml
      core_switch_num: 1
      client_switches: 9
      clients: 9
  mesh:
    details:
      switches: 5
      client_switches: 2
      clients: 9
  fat_tree:
    details:
      clients : 9
      leaf_switch_layers : 2
      fanout: 3




